--
CREATE TABLE EMPLOYEES
 (	
  EMPLOYEE_ID    INT NOT NULL,
	FIRST_NAME     VARCHAR(20 ), 
	LAST_NAME      VARCHAR(25 ),
	EMAIL          VARCHAR(25 ) ,
	PHONE_NUMBER   VARCHAR(20 ), 
	HIRE_DATE      DATETIME,
	JOB_ID         VARCHAR(10 ),
	SALARY         INT, 
	COMMISSION_PCT INT, 
	MANAGER_ID     INT,
	DEPARTMENT_ID  INT
);	

 ALTER TABLE EMPLOYEES
 ADD CONSTRAINT EMPLOYEES_PK PRIMARY KEY (EMPLOYEE_ID);

CREATE TABLE DEPARTMENTS
 (	
	DEPARTMENT_ID  INT NOT NULL,
	DEPARTMENT_NAME  VARCHAR(80),
	MANAGER_ID     INT,
	LOCATION_ID    INT
);	


 ALTER TABLE DEPARTMENTS
 ADD CONSTRAINT DEPARTMENTS_PK PRIMARY KEY (DEPARTMENT_ID);
 
 