-- Subquery_ Basic
-- The importance of read order
/*
SELECT * 
FROM (SELECT * FROM EMPLOYEES  ORDER BY HIRE_DATE DESC)
WHERE ROWNUM BETWEEN 1 AND 10;
*/

SELECT *
FROM EMPLOYEES
WHERE SALARY >= (SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT AVG(SALARY) FROM EMPLOYEES GROUP BY SALARY;